### ISSUE TITLE
Does call_soon work with normal functions ?

### ISSUE THREAD

**Issue by stuaxo** [nathan-hoad/gbulb#11]
If I do this, then my dummy func never seems to get called:

```
        def dummy_func():
            print("DUMMY FUNC")
            print(args)
            print(kwargs)

     loop.call_soon(dummy_func)
```

**Comment by nathan-hoad** [comment]
Can you provide a reproducible example? Because it works for me:

```
nhoad@nhoad-laptop ~ $ cat callsoon.py 
import gbulb
gbulb.install()

loop = gbulb.get_event_loop()


def hello():
    print('hello')


loop.call_soon(hello)
loop.run_forever()
nhoad@nhoad-laptop ~ $ python callsoon.py 
hello
^CTraceback (most recent call last):
  File "callsoon.py", line 12, in <module>
    loop.run_forever()
  File "/home/nhoad/.local/lib/python3.5/site-packages/gbulb/glib_events.py", line 348, in run_forever
    super().run_forever()
  File "/home/nhoad/.local/lib/python3.5/site-packages/gbulb/glib_events.py", line 145, in run_forever
    self.run()
  File "/home/nhoad/.local/lib/python3.5/site-packages/gbulb/glib_events.py", line 324, in run
    self._mainloop.run()
  File "/usr/lib/python3.5/site-packages/gi/overrides/GLib.py", line 577, in run
    raise KeyboardInterrupt
KeyboardInterrupt
```

**Comment by stuaxo** [comment]
Hm, I've since reorganised my code, so don't have whatever I was trying.

Since I know this should work, I'll shut this for now, then re-open if I reproduce it.

Thanks for gbulb :)
