### ISSUE TITLE
Working with DBus

### ISSUE THREAD

**Issue by miguelvalerio** [nathan-hoad/gbulb#21]
I'm having trouble getting the GLib loop to work with DBus. The test case can be summarized to this:

```python
import asyncio, gbulb
gbulb.install()
import dbus

loop = asyncio.get_event_loop()
session_bus = dbus.SessionBus(mainloop=loop)
```

This code throws the following exception:
```
Traceback (most recent call last):
  File "new_t.py", line 11, in <module>
    session_bus = dbus.SessionBus(mainloop=loop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
TypeError: A dbus.mainloop.NativeMainLoop instance is required
```

Any tips on how I can fix this issue?

**Comment by astronouth7303** [comment]
It's looking for a `dbus` loop, not an `asyncio` one. If you don't pass it any loop, I believe it'll ask glib for the current loop.

**Comment by TingPing** [comment]
You shouldn't be using `dbus-python` in the first place, use GDBus that is a core part of Gio.

**Comment by miguelvalerio** [comment]
So, quick little update. I was lacking the following lines
```python
from dbus.mainloop.glib import DBusGMainLoop
DBusGMainLoop(set_as_default=True)
```
right after calling `gbulb.install()`. After that all I had to do was perform some basic changes in order to get the `wait_signal` future to call `connect_to_signal` instead of `connect`. After these changes i can successfully register signal handlers in DBus.

**Comment by nathan-hoad** [comment]
If you'd be interested in contributing an example of what you've done to get this working, I'd be happy to accept it!

**Comment by HQJaTu** [comment]
Example GLib and asyncio combined loop code into `examples/`.

```python
import sys
from gi.repository import GLib
import gbulb
import asyncio
import logging

log = logging.getLogger(__name__)


def tick() -> bool:
    """
    Glib asynchronous task
    :return: bool, true=run next interval, false=stop
    """
    log.warning("Tick")

    # Keep GLib ticking
    return True


async def boom() -> None:
    """
    asyncio task
    :return:
    """
    while await asyncio.sleep(5, result=True):
        log.error("BOOM!")


def main() -> None:
    # Logging
    log_formatter = logging.Formatter("%(asctime)s [%(threadName)-12.12s] [%(levelname)-5.5s]  %(message)s")
    console_handler = logging.StreamHandler(sys.stderr)
    console_handler.setFormatter(log_formatter)
    console_handler.propagate = False
    log.addHandler(console_handler)
    log.setLevel(logging.DEBUG)

    # Gbulb and asyncio setup
    gbulb.install(gtk=False)
    asyncio.set_event_loop_policy(gbulb.GLibEventLoopPolicy())
    loop = asyncio.get_event_loop()

    # Glib-loop task to be executed every second
    GLib.timeout_add_seconds(1, tick)

    # asyncio-loop task
    task = loop.create_task(boom())

    # stop-task
    # Run for 30 seconds, then done.
    loop.call_later(30, task.cancel)

    # Go loop until stop()
    log.info("Going for asyncio event loop using GLib main loop")
    try:
        # loop.run_forever()
        loop.run_until_complete(task)
    except KeyboardInterrupt:
        # Avoid "Task was destroyed but it is pending!" -error
        # GLib task doesn't need cancelling.
        task.cancel()
    except asyncio.CancelledError:
        # asyncio task is already cancelled
        # GLib task doesn't need cancelling.
        pass
    finally:
        loop.run_until_complete(loop.shutdown_asyncgens())
        loop.close()
    log.info("Done.")


if __name__ == "__main__":
    main()
```
