### ISSUE TITLE
Python 3.7 incompatibilities in GLibBaseEventLoop._make_ssl_transport()

### ISSUE THREAD

**Issue by philn** [nathan-hoad/gbulb#37]
test-case:
```
import aiohttp
import asyncio
import gbulb
gbulb.install()

async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def main():
    connector = aiohttp.TCPConnector()

    async with aiohttp.ClientSession(connector=connector) as session:
        html = await fetch(session, 'http://python.org')
        print(html)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Error:
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    loop.run_until_complete(main())
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/gbulb/glib_events.py", line 731, in run_until_complete
    return future.result()
  File "test.py", line 14, in main
    html = await fetch(session, 'http://python.org')
  File "test.py", line 7, in fetch
    async with session.get(url) as response:
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/aiohttp/client.py", line 366, in _request
    timeout=timeout
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/aiohttp/connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "/Users/philn/Library/Python/3.7/lib/python/site-packages/aiohttp/connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 970, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 993, in _create_connection_transport
    ssl_handshake_timeout=ssl_handshake_timeout)
TypeError: _make_ssl_transport() got an unexpected keyword argument 'ssl_handshake_timeout'
```

This seems simple to fix, I'll give it a try.

**Comment by philn** [comment]
More :(
```
  File "/Users/philn/dev/gbulb/gbulb/glib_events.py", line 288, in _make_ssl_transport
    if not sslproto._is_sslproto_available():
AttributeError: module 'asyncio.sslproto' has no attribute '_is_sslproto_available'

```

**Comment by nathan-hoad** [comment]
Ah! That code with context:

        if not sslproto._is_sslproto_available():
            raise NotImplementedError("Proactor event loop requires Python 3.5"
                                      " or newer (ssl.MemoryBIO) to support "
                                      "SSL")

So it looks like a leftover check for 3.4.x, we should be able to completely remove that conditional I'm pretty sure.

Thank you for reporting and taking a look at this!

**Comment by philn** [comment]
Ah remove really? It might still be useful for Python <= 3.6 ? For now I added a runtime check but if this can safely be removed then I can update the PR :)

**Comment by nathan-hoad** [comment]
That's okay! I'll try and do some testing with older versions of Python over the weekend and see if it can be removed :)
